apiVersion: apps/v1
kind: Deployment
metadata:
  name: reporter-server
  namespace: stage
spec:
  template:
    spec:
      containers:
      - name: reporter-server
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "stage"
---
apiVersion: v1
kind: Service
metadata:
  name: reporter-server
  namespace: stage
